// AUTO-GENERATED by scripts/build-board-facility-classic.mjs. DO NOT EDIT.
// Source of truth: browser/board-facility-state-core.mjs
(function installBoardFacilityClassicBridge(global) {
  'use strict';
  const GLOBAL_NAME = "GAMEROAD_BOARD_FACILITY_STATE_CORE";
  const BRIDGE_VERSION = "gameroad.board-facility-classic-bridge.v1";
  const EXPECTED_EXPORTS = Object.freeze(["createBoardFacilityState", "purchaseShopProduct", "beginFacilityRound", "depositArenaCard", "prepareArenaBattle", "resolveArenaBattle", "settleArena", "endFacilityMatch", "BOARD_FACILITY_STATE_CORE"]);
  if (!global || (typeof global !== 'object' && typeof global !== 'function')) {
    throw new Error('BOARD_FACILITY_GLOBAL_REQUIRED');
  }
  if (Object.prototype.hasOwnProperty.call(global, GLOBAL_NAME)) {
    const existing = global[GLOBAL_NAME];
    if (existing && existing.bridgeVersion === BRIDGE_VERSION) return;
    throw new Error('BOARD_FACILITY_GLOBAL_COLLISION');
  }
  let core = null;
  let loadError = null;
  function requireCore() {
    if (core) return core;
    if (loadError) {
      const error = new Error('BOARD_FACILITY_CORE_LOAD_FAILED');
      error.cause = loadError;
      throw error;
    }
    throw new Error('BOARD_FACILITY_CORE_NOT_READY');
  }
  const api = {
    bridgeVersion: BRIDGE_VERSION,
    expectedExports: EXPECTED_EXPORTS,
    isReady() { return core !== null; },
    createBoardFacilityState(...args) { return requireCore().createBoardFacilityState(...args); },
    purchaseShopProduct(...args) { return requireCore().purchaseShopProduct(...args); },
    beginFacilityRound(...args) { return requireCore().beginFacilityRound(...args); },
    depositArenaCard(...args) { return requireCore().depositArenaCard(...args); },
    prepareArenaBattle(...args) { return requireCore().prepareArenaBattle(...args); },
    resolveArenaBattle(...args) { return requireCore().resolveArenaBattle(...args); },
    settleArena(...args) { return requireCore().settleArena(...args); },
    endFacilityMatch(...args) { return requireCore().endFacilityMatch(...args); },
  };
  Object.defineProperty(api, "BOARD_FACILITY_STATE_CORE", { enumerable: true, get() { return requireCore().BOARD_FACILITY_STATE_CORE; } });
  const ready = import('./board-facility-state-core.mjs').then(namespace => {
    for (const name of EXPECTED_EXPORTS) {
      if (!Object.prototype.hasOwnProperty.call(namespace, name)) {
        throw new Error('BOARD_FACILITY_CORE_EXPORT_MISSING:' + name);
      }
    }
    core = namespace;
    return api;
  }).catch(error => {
    loadError = error;
    throw error;
  });
  Object.defineProperty(api, 'ready', { enumerable: true, value: ready });
  Object.freeze(api);
  Object.defineProperty(global, GLOBAL_NAME, {
    configurable: false,
    enumerable: true,
    writable: false,
    value: api,
  });
})(globalThis);
